os:
  - linux
  - osx
language: node_js
node_js:
- '10'
branches:
  only:
  - master
before_script:
- npm install -g @vue/cli
- npm install
script:
- npm run electron:build
deploy:
  provider: releases
  skip_cleanup: true
  on:
    branch: master
